export enum SenegalLandmark {
  YOFF_BCEAO = "YOFF_BCEAO",
  YOFF_DIAMALAYE = "YOFF_DIAMALAYE",
  YOFF_APECSY = "YOFF_APECSY",
  YOFF_MARATHON = "YOFF_MARATHON",
  YOFF_ECO_BANK = "YOFF_ECO_BANK",
  YOFF_VIRAGE = "YOFF_VIRAGE",
  YOFF_BIAGUI = "YOFF_BIAGUI",
  YOFF_ROND_POINT = "YOFF_ROND_POINT",
  YOFF_SDE = "YOFF_SDE",
  YOFF_OCEAN = "YOFF_OCEAN",
  YOFF_CITÉ_DJILI_MBAYE = "YOFF_CITÉ_DJILI_MBAYE",
  YOFF_DIAMALAYE_BRIOCHE_DOREE = "YOFF_DIAMALAYE_BRIOCHE_DOREE",
  YOFF_BRIOCHE_DOREE = "YOFF_BRIOCHE_DOREE",
  YOFF_MARCHE = "YOFF_MARCHE",
  YOFF_LAYENNE = "YOFF_LAYENNE",
  YOFF_SENELEC = "YOFF_SENELEC",
  YOFF_ONOMO = "YOFF_ONOMO",
  YOFF_AUCHAN = "YOFF_AUCHAN",
  YOFF_NDEUGAGNE = "YOFF_NDEUGAGNE",
  YOFF_TONGHOR = "YOFF_TONGHOR",

  GRAND_YOFF_COTE_BRT = "GRAND_YOFF_COTE_BRT",
  GRAND_YOFF_CITE_MILLIONNAIRE = "GRAND_YOFF_CITE_MILLIONNAIRE",
  GRAND_YOFF_CTO = "GRAND_YOFF_CTO",
  GRAND_YOFF_EGLISE = "GRAND_YOFF_EGLISE",
  GRAND_YOFF_BRIOCHE_DOREE = "GRAND_YOFF_BRIOCHE_DOREE",
  GRAND_YOFF_VERS_POLICE = "GRAND_YOFF_VERS_POLICE",
  GRAND_YOFF_FOYER_DES_JEUNES = "GRAND_YOFF_FOYER_DES_JEUNES",

  NORD_FOIRE_YUM_YUM = "NORD_FOIRE_YUM_YUM",
  NORD_FOIRE_BANK_OF_AFRICA = "NORD_FOIRE_BANK_OF_AFRICA",
  NORD_FOIRE_BRIOCHE_DOREE = "NORD_FOIRE_BRIOCHE_DOREE",
  NORD_FOIRE_SDE = "NORD_FOIRE_SDE",
  NORD_FOIRE_TERRAIN_BASKET = "NORD_FOIRE_TERRAIN_BASKET",
  NORD_FOIRE_VDN = "NORD_FOIRE_VDN",
  NORD_FOIRE_CITE_MIXTA = "NORD_FOIRE_CITE_MIXTA",

  OUEST_FOIRE_BANQUE_CBAO = "OUEST_FOIRE_BANQUE_CBAO",
  OUEST_FOIRE_AUTOROUTE_TERMINUS_BUS = "OUEST_FOIRE_AUTOROUTE_TERMINUS_BUS",
  OUEST_FOIRE_CASE_DES_TOUTS_PETITS = "OUEST_FOIRE_CASE_DES_TOUTS_PETITS",
  OUEST_FOIRE_FEDERATION_FOOTBALL = "OUEST_FOIRE_FEDERATION_FOOTBALL",
  OUEST_FOIRE_BARA_COUTURE = "OUEST_FOIRE_BARA_COUTURE",
  OUEST_FOIRE_BRIOCHE_DOREE = "OUEST_FOIRE_BRIOCHE_DOREE",
  OUEST_FOIRE_PHARMACIE_SABARA = "OUEST_FOIRE_PHARMACIE_SABARA",
  OUEST_FOIRE_PHARMACIE_XANDAR = "OUEST_FOIRE_PHARMACIE_XANDAR",

  HLM_GRAND_YOFF_DIBITERIE_KOROMACK_FAYE = "HLM_GRAND_YOFF_DIBITERIE_KOROMACK_FAYE",
  HLM_GRAND_YOFF_HOTEL_SOUM_SOUM = "HLM_GRAND_YOFF_HOTEL_SOUM_SOUM",
  HLM_GRAND_YOFF_ECOLE_PEDAGOGUE = "HLM_GRAND_YOFF_ECOLE_PEDAGOGUE",
  HLM_GRAND_YOFF_TERMINUS_AIBD = "HLM_GRAND_YOFF_TERMINUS_AIBD",

  SICAP_FOIRE_TOUBA_OIL = "SICAP_FOIRE_TOUBA_OIL",
  SICAP_FOIRE_PORTE_CICES = "SICAP_FOIRE_PORTE_CICES",
  SICAP_FOIRE_YOFF_DIBITERIE_KOROMACK_FAYE = "SICAP_FOIRE_YOFF_DIBITERIE_KOROMACK_FAYE",
  SICAP_FOIRE_LONASE = "SICAP_FOIRE_LONASE",
  SICAP_FOIRE_RÉSIDENCE_DABA = "SICAP_FOIRE_RÉSIDENCE_DABA",
  SICAP_FOIRE_VDN = "SICAP_FOIRE_VDN",
  SICAP_FOIRE_PRESTIGE_DECO = "SICAP_FOIRE_PRESTIGE_DECO",

  OUAKAM_STATION_SHELL = "OUAKAM_STATION_SHELL",
  OUAKAM_TERMINUS_P7 = "OUAKAM_TERMINUS_P7",
  OUAKAM_TERMINUS_43 = "OUAKAM_TERMINUS_43",
  OUAKAM_COMICO = "OUAKAM_COMICO",
  OUAKAM_CITE_AVION = "OUAKAM_CITE_AVION",
  OUAKAM_BRIOCHE_DOREE = "OUAKAM_BRIOCHE_DOREE",
  OUAKAM_MACKYOU_FAYE = "OUAKAM_MACKYOU_FAYE",
  OUAKAM_ROND_POINT_MONUMENT = "OUAKAM_ROND_POINT_MONUMENT",
  OUAKAM_SUPER_MARCHE_MON_PRIX = "OUAKAM_SUPER_MARCHE_MON_PRIX",
  OUAKAM_MAMELLE = "OUAKAM_MAMELLE",
  OUAKAM_CITE_BALLON = "OUAKAM_CITE_BALLON",
  OUAKAM_AUCHAN = "OUAKAM_AUCHAN",
  OUAKAM_PHARMACIE_YAYE_AMINATA = "OUAKAM_PHARMACIE_YAYE_AMINATA",

  LIBERTE_6_PHARMACIE_CAMP_LECLERC = "LIBERTE_6_PHARMACIE_CAMP_LECLERC",
  LIBERTE_6_PENTOLA = "LIBERTE_6_PENTOLA",
  LIBERTE_6_DIBITERIE_OUBA = "LIBERTE_6_DIBITERIE_OUBA",
  LIBERTE_6_STATION = "LIBERTE_6_STATION",
  LIBERTE_6_MARCHE_BARACK = "LIBERTE_6_MARCHE_BARACK",
  LIBERTE_6_NUMERO_UNO = "LIBERTE_6_NUMERO_UNO",
  LIBERTE_6_IMMEUBLE_FERDINAND_COLY = "LIBERTE_6_IMMEUBLE_FERDINAND_COLY",
  LIBERTE_6_AUCHAN = "LIBERTE_6_AUCHAN",
  LIBERTE_6_VDN = "LIBERTE_6_VDN",
  LIBERTE_6_HYUNDAI_VDN = "LIBERTE_6_HYUNDAI_VDN",
  LIBERTE_6_CAMP_PENAL = "LIBERTE_6_CAMP_PENAL",
  LIBERTE_6_PRISONS_POUR_FEMME = "LIBERTE_6_PRISONS_POUR_FEMME",
  LIBERTE_6_SONATEL_2 = "LIBERTE_6_SONATEL_2",

  HLM_SODIA = "HLM_SODIA",
  HLM_POSTE_SANTE = "HLM_POSTE_SANTE",
  HLM_6 = "HLM_6",
  HLM_RAIL = "HLM_RAIL",
  HLM_STATION = "HLM_STATION",

  CASTOR_SODIDA = "CASTOR_SODIDA",
  CASTOR_BRIOCHE_DOREE = "CASTOR_BRIOCHE_DOREE",
  CASTOR_AUCHAN = "CASTOR_AUCHAN",
  CASTOR_SENELEC = "CASTOR_SENELEC",

  PATTE_DOIE_BRT = "PATTE_DOIE_BRT",

  MAMELLE_CITE_CHEIKH_AMAR = "MAMELLE_CITE_CHEIKH_AMAR",
  MAMELLE_CITE_MBACKIYOU_FAYE = "MAMELLE_CITE_MBACKIYOU_FAYE",
  MAMELLE_CITE_TOUBA_RENAISSANCE = "MAMELLE_CITE_TOUBA_RENAISSANCE",
  MAMELLE_RESTAURANT_MELO = "MAMELLE_RESTAURANT_MELO",
  MAMELLE_ECOLE_SEMAD = "MAMELLE_ECOLE_SEMAD",

  SUD_FOIRE_ECOLE_IQRA = "SUD_FOIRE_ECOLE_IQRA",

  DIEUPPEUL_TERRAIN_BASKET = "DIEUPPEUL_TERRAIN_BASKET",

  PARCELLE_ASSAINIE_ROND_POINT_26 = "PARCELLE_ASSAINIE_ROND_POINT_26",
  PARCELLE_ASSAINIE_CITE_FADIA = "PARCELLE_ASSAINIE_CITE_FADIA",
  PARCELLE_ASSAINIE_CITÉ_DAMEL = "PARCELLE_ASSAINIE_CITÉ_DAMEL",

  ZAC_MBAO_ROND_POINT_SIPRES = "ZAC_MBAO_ROND_POINT_SIPRES",
  ZAC_MBAO_CITE_SONATEL = "ZAC_MBAO_CITE_SONATEL",

  OUEST_FOIRE_ROND_POINT_YOFF = "OUEST_FOIRE_ROND_POINT_YOFF",
  OUEST_FOIRE_MARCHÉ_SERIGNE_FALLOU = "OUEST_FOIRE_MARCHÉ_SERIGNE_FALLOU",
  OUEST_FOIRE_ECOLE_DE_FORMATION_MEDECINE_SAMBA_DIALLO = "OUEST_FOIRE_ECOLE_DE_FORMATION_MEDECINE_SAMBA_DIALLO",

  HLM_GRAND_YOFF_BRT_HYACINTHE_THIANDOUM = "HLM_GRAND_YOFF_BRT_HYACINTHE_THIANDOUM",
  HLM_GRAND_YOFF_ECOLE_YASINE_THIANDOU = "HLM_GRAND_YOFF_ECOLE_YASINE_THIANDOU",
  HLM_GRAND_YOFF_HOPITAL_AMERICAIN = "HLM_GRAND_YOFF_HOPITAL_AMERICAIN",
  HLM_GRAND_YOFF_RESIDENCES_ATAYA = "HLM_GRAND_YOFF_RESIDENCES_ATAYA",
  HLM_GRAND_YOFF_EN_FACE_STADE_AMITIE = "HLM_GRAND_YOFF_EN_FACE_STADE_AMITIE",

  SICAP_FOIRE_CITE_MAGISTRAT = "SICAP_FOIRE_CITE_MAGISTRAT",
  SICAP_FOIRE_GENDARMERIE = "SICAP_FOIRE_GENDARMERIE",

  OUAKAM_CROISEMENT = "OUAKAM_CROISEMENT",

  LIBERTE_6_SAMU = "LIBERTE_6_SAMU",
  LIBERTE_6_CSE = "LIBERTE_6_CSE",
  LIBERTE_6_CITE_SONATEL = "LIBERTE_6_CITE_SONATEL",
  LIBERTE_6_CITE_ALIOU_SOW = "LIBERTE_6_CITE_ALIOU_SOW",
  LIBERTE_6_TERRAIN_FOOTBALL = "LIBERTE_6_TERRAIN_FOOTBALL",

  HLM_CITE_DOUANE = "HLM_CITE_DOUANE",
  HLM_MASSALIKOUL_DJINANE = "HLM_MASSALIKOUL_DJINANE",
  HLM_EDK = "HLM_EDK",

  CASTOR_TERRAIN_FOOTBALL = "CASTOR_TERRAIN_FOOTBALL",

  GRAND_DAKAR_RESTAURANT_LE_COQ = "GRAND_DAKAR_RESTAURANT_LE_COQ",
  GRAND_DAKAR_BRT = "GRAND_DAKAR_BRT",

  PARCELLE_ASSAINIE_26_STADE = "PARCELLE_ASSAINIE_26_STADE",

  LIBERTE_4_TERRAIN_FOOTBALL = "LIBERTE_4_TERRAIN_FOOTBALL",
  LIBERTE_4_TERMINUS = "LIBERTE_4_TERMINUS",
  LIBERTE_4_IPG = "LIBERTE_4_IPG",

  SCAT_URBAM_TERRAIN_FOOTBALL = "SCAT_URBAM_TERRAIN_FOOTBALL",
  SCAT_URBAM_STATION_OLIBIA = "SCAT_URBAM_STATION_OLIBIA",
  SCAT_URBAM_MOSQUEE = "SCAT_URBAM_MOSQUEE",

  MEDINA_BRIOCHE_DOREE = "MEDINA_BRIOCHE_DOREE",

  HLM_GRAND_MEDINE_VDN = "HLM_GRAND_MEDINE_VDN",

  FASS_MARCHE = "FASS_MARCHE",

  NGOR_CHEZ_KATHIA = "NGOR_CHEZ_KATHIA",

  ALMADIES_ECOLE_BILLINGUE = "ALMADIES_ECOLE_BILLINGUE",

  SACRE_COEUR_VDN = "SACRE_COEUR_VDN",
  SACRE_COEUR_RESIDENCE_MAMOUNE = "SACRE_COEUR_RESIDENCE_MAMOUNE",
  SACRE_COEUR_BOULANGERIE_JAUNE = "SACRE_COEUR_BOULANGERIE_JAUNE",
  SACRE_COEUR_CITE_BATRAIN = "SACRE_COEUR_CITE_BATRAIN",

  ZONE_DE_CAPTAGE_BRIOCHE_DOREE = "ZONE_DE_CAPTAGE_BRIOCHE_DOREE",

  KHAR_YALLA_BRT = "KHAR_YALLA_BRT",
  KHAR_YALLA_STATION = "KHAR_YALLA_STATION",

  MERMOZ_CHINA_MALL = "MERMOZ_CHINA_MALL",
  MERMOZ_SICAP_BAOBAB = "MERMOZ_SICAP_BAOBAB",
  MERMOZ_CITE_KEUR_GORGUI = "MERMOZ_CITE_KEUR_GORGUI",
  MERMOZ_SOTRAC = "MERMOZ_SOTRAC",

  CITE_SAFCO_CROISMENT_KEURMASSAR = "CITE_SAFCO_CROISMENT_KEURMASSAR",

  PETIT_MBAO_CITE_ADJA_MAREME = "PETIT_MBAO_CITE_ADJA_MAREME",
}
