export enum SenegalCity {
  YOFF = "YOFF",
  GRAND_YOFF = "GRAND_YOFF",
  NORD_FOIRE = "NORD_FOIRE",
  OUEST_FOIRE = "OUEST_FOIRE",
  HLM_GRAND_YOFF = "HLM_GRAND_YOFF",
  SICAP_FOIRE = "SICAP_FOIRE",
  OUAKAM = "OUAKAM",
  LIBERTE_6 = "LIBERTE_6",
  HLM = "HLM",
  CASTOR = "CASTOR",
  DIEUPPEUL_DERKLE = "DIEUPPEUL_DERKLE",
  PLATEAU = "PLATEAU",
  PATTE_DOIE = "PATTE_DOIE",
  BISCUITERIE = "BISCUITERIE",
  SUD_FOIRE = "SUD_FOIRE",
  PARCELLE_ASSAINIE = "PARCELLE_ASSAINIE",
  SCAT_URBAM = "SCAT_URBAM",
  NIARY_TALLY = "NIARY_TALLY",
  BENE_TALLY = "BENE_TALLY",
  GIBRALTAR = "GIBRALTAR",
  CAMBERENE = "CAMBERENE",
  MEDINA = "MEDINA",
  LIBERTE_4 = "LIBERTE_4",
  LIBERTE_3 = "LIBERTE_3",
  LIBERTE_2 = "LIBERTE_2",
  HLM_GRAND_MEDINE = "HLM_GRAND_MEDINE",
  GRAND_DAKAR = "GRAND_DAKAR",
  MAMELLE = "MAMELLE",
  ZONE_DE_CAPTAGE = "ZONE_DE_CAPTAGE",
  KHAR_YALLA = "KHAR_YALLA",
  FANN = "FANN",
  LIBERTE_1 = "LIBERTE_1",
  LIBERTE_5 = "LIBERTÉ_5",
  POINT_E = "POINT_E",
  SICAP_KARACK = "SICAP_KARACK",
  FASS = "FASS",
  NGOR = "NGOR",
  ALMADIES = "ALMADIES",
  GUEULE_TAPEE = "GUEULE_TAPEE",
  SACRE_COEUR = "SACRE_COEUR",
  MERMOZ = "MERMOZ",
  CITE_KEUR_GORGUI = "CITE_KEUR_GORGUI",
  AMITIE = "AMITIE",
  COLOBANE = "COLOBANE",
  HANN_MARISTE = "HANN_MARISTE",
  HANN_BEL_AIR = "HANN_BEL_AIR",
  GOREE = "GOREE",
  GOLF = "GOLF",
  GADAYE = "GADAYE",
  WAKHINANE_NIMZATT = "WAKHINANE_NIMZATT",
  NDIAREME_LIMAMOULAYE = "NDIAREME_LIMAMOULAYE",
  SAM_NOTAIRE = "SAM_NOTAIRE",
  MEDINA_GOUNASS = "MEDINA_GOUNASS",
  CITE_FADIA = "CITE_FADIA",
  MALIKA = "MALIKA",
  ALMADIE_2 = "ALMADIE_2",
  KEUR_MASSAR = "KEUR_MASSAR",
  JAXAAY = "JAXAAY",
  FASS_MBAO = "FASS_MBAO",
  DALIFORT = "DALIFORT",
  YEUMBEUL = "YEUMBEUL",
  THIAROYE = "THIAROYE",
  DIAMAGUENE = "DIAMAGUENE",
  TIVAOUANE_DIAKSAO = "TIVAOUANE_DIAKSAO",
  GUINAW_RAILS = "GUINAW_RAILS",
  PIKINE = "PIKINE",
  KEUR_MBAYE_FALL = "KEUR_MBAYE_FALL",
  PETIT_MBAO = "PETIT_MBAO",
  GRAND_MBAO = "GRAND_MBAO",
  ZAC_MBAO = "ZAC_MBAO",
  RUFISQUE = "RUFISQUE",
  BARGNY = "BARGNY",
  KOUNOUNE = "KOUNOUNE",
  LAC_ROSE = "LAC_ROSE",
  NDIAKHIRATE = "NDIAKHIRATE",
  DIAMNIADIO = "DIAMNIADIO",
  BAMBILOR = "BAMBILOR",
  NIAGUE = "NIAGUE",
  KEUR_NDIAYE_LO = "KEUR_NDIAYE_LO",
  DENI_GUEDJ = "DENI_GUEDJ",
  TIVAOUANE_PEULH = "TIVAOUANE_PEULH",
  GRAND_STANDING = "GRAND_STANDING",
  PARCELLE_ASSAINIE_THIES = "PARCELLE_ASSAINIE_THIES",
  MBOUR_4 = "MBOUR_4",
  DIXIEME = "DIXIEME",
  MEDINA_FALL = "MEDINA_FALL",
  HERSENT = "HERSENT",
  KEUR_ISSA = "KEUR_ISSA",
  POUT = "POUT",
  SALY = "SALY",
  NGUEKOKH = "NGUEKOKH",
  SINDIA = "SINDIA",
  NGUERIGNE_BAMBARA = "NGUERIGNE_BAMBARA",
  TOUBAB_DIALAW = "TOUBAB_DIALAW",
  NIANING = "NIANING",
  WARANG = "WARANG",
  MALICOUNDA = "MALICOUNDA",
  MBOUR = "MBOUR",
  NGAPAROU = "NGAPAROU",
  SOMONE = "SOMONE",

  /**
   * Sébikotane
   * noflaye
   *
   *
   *
   * Fahu
   * Nguinth
   * Mbour 3
   * Diakhao
   * Thialy
   * Randouléne Nord
   * Mbour 1
   * Thies Nones
   * Cité Lamy
   * Mbour 2
   * Cité Senghor
   * Mbambara
   * Sampathe
   * Carrière
   * Escale Nord
   * Randouléne Sud
   * Diamaguene
   * Keur Tiem Savare
   * Som
   * Hlm Thialy
   * Keur Ablaye Yakhine
   * SOFRACO
   * Escale Sud
   * Keurykao
   * cite Ibrahima Sarr Ex ballabey
   * Cité Ousmane Ngom
   * Cité Niakh
   * Zone Industrielle
   * quartier Darou Salam
   * HLM Route de Mbour
   * Quartier Bahdate
   *
   * pout
   */
}
