export enum SenegalDepartment {
  DAKAR = "DAKAR",
  PIKINE = "PIKINE",
  GUEDIAWAYE = "GUEDIAWAYE",
  RUFISQUE = "RUFISQUE",
  KEUR_MASSAR = "KEUR_MASSAR",
  THIES = "THIES",
  PETITE_COTE = "PETITE_COTE",
}
