import { SenegalCity } from "./senegal.city";
import { SenegalDepartment } from "./senegal.department";
import { SenegalLandmark } from "./senegal.landmark";

export const SENEGAL_NEIGHBORHOODS = {
  [SenegalDepartment.DAKAR]: {
    [SenegalCity.YOFF]: [
      SenegalLandmark.YOFF_BCEAO,
      SenegalLandmark.YOFF_DIAMALAYE,
      SenegalLandmark.YOFF_APECSY,
      SenegalLandmark.YOFF_MARATHON,
      SenegalLandmark.YOFF_ECO_BANK,
      SenegalLandmark.YOFF_VIRAGE,
      SenegalLandmark.YOFF_BIAGUI,
      SenegalLandmark.YOFF_ROND_POINT,
      SenegalLandmark.YOFF_SDE,
      SenegalLandmark.YOFF_OCEAN,
      SenegalLandmark.YOFF_CITÉ_DJILI_MBAYE,
      SenegalLandmark.YOFF_BRIOCHE_DOREE,
      SenegalLandmark.YOFF_MARCHE,
      SenegalLandmark.YOFF_LAYENNE,
      SenegalLandmark.YOFF_SENELEC,
      SenegalLandmark.YOFF_ONOMO,
      SenegalLandmark.YOFF_AUCHAN,
      SenegalLandmark.YOFF_NDEUGAGNE,
      SenegalLandmark.YOFF_TONGHOR,
      SenegalLandmark.YOFF_BIAGUI_BRIOCHE_DOREE,
      SenegalLandmark.YOFF_DIAMALAYE_TERMINUS,
      SenegalLandmark.YOFF_DIAMALAYE_BRIOCHE_DOREE,
      SenegalLandmark.YOFF_AEROPORT,
      SenegalLandmark.YOFF_VIRAGE_NSIA,
      SenegalLandmark.YOFF_BIAGUI_HYPERMARCHÉ_EXCLUSIF,
      SenegalLandmark.YOFF_TALLY_CLANDO,
      SenegalLandmark.YOFF_NDENATT,
      SenegalLandmark.YOFF_DEPOT_GAZ,
      SenegalLandmark.YOFF_CIMETIAIRE,
      SenegalLandmark.YOFF_BIAGUI_PONT_SAKAM,
      SenegalLandmark.YOFF_APECSY_MADAWAS,
      SenegalLandmark.YOFF_CENTRE_AEREE_BCEAO,
    ],

    [SenegalCity.GRAND_YOFF]: [
      SenegalLandmark.GRAND_YOFF_COTE_BRT,
      SenegalLandmark.GRAND_YOFF_CITE_MILLIONNAIRE,
      SenegalLandmark.GRAND_YOFF_CTO,
      SenegalLandmark.GRAND_YOFF_EGLISE,
      SenegalLandmark.GRAND_YOFF_BRIOCHE_DOREE,
      SenegalLandmark.GRAND_YOFF_VERS_POLICE,
      SenegalLandmark.GRAND_YOFF_FOYER_DES_JEUNES,
      SenegalLandmark.GRAND_YOFF_ARAFAT,
      SenegalLandmark.GRAND_YOFF_ANCIENNE_MAIRIE,
      SenegalLandmark.GRAND_YOFF_ZONE_DE_CAPTAGE,
      SenegalLandmark.GRAND_YOFF_MARCHE,
    ],

    [SenegalCity.GRAND_DAKAR]: [
      SenegalLandmark.GRAND_DAKAR_RESTAURANT_LE_COQ,
      SenegalLandmark.GRAND_DAKAR_BRT,
      SenegalLandmark.GRAND_DAKAR_MASSALIKOUL_DJINANE,
      SenegalLandmark.GRAND_DAKAR_EDK,
      SenegalLandmark.GRAND_DAKAR_ZONE_A,
      SenegalLandmark.GRAND_DAKAR_CENTENAIRE,
      SenegalLandmark.GRAND_DAKAR_PHARMACIE_EMMANUELLE,
      SenegalLandmark.GRAND_DAKAR_MARCHE,
      SenegalLandmark.GRAND_DAKAR_GARAGE_CASAMANCE,
      SenegalLandmark.GRAND_DAKAR_ZONE_B,
      SenegalLandmark.GRAND_DAKAR_ROND_POINT_DIEUPEUL,
      SenegalLandmark.GRAND_DAKAR_AMITIE,
    ],

    [SenegalCity.NORD_FOIRE]: [
      SenegalLandmark.NORD_FOIRE_YUM_YUM,
      SenegalLandmark.NORD_FOIRE_BANK_OF_AFRICA,
      SenegalLandmark.NORD_FOIRE_BRIOCHE_DOREE,
      SenegalLandmark.NORD_FOIRE_SDE,
      SenegalLandmark.NORD_FOIRE_TERRAIN_BASKET,
      SenegalLandmark.NORD_FOIRE_VDN,
      SenegalLandmark.NORD_FOIRE_CITE_MIXTA,
      SenegalLandmark.NORD_FOIRE_ROND_26,
      SenegalLandmark.NORD_FOIRE_CITE_BCEAO,
      SenegalLandmark.NORD_FOIRE_WALLY_SECK,
      SenegalLandmark.NORD_FOIRE_AUTOROUTE_AEROPORT_LEOPOLD,
      SenegalLandmark.NORD_FOIRE_AUCHAN,
      SenegalLandmark.NORD_FOIRE_CITE_ATAYA,
      SenegalLandmark.NORD_FOIRE_KEUR_YOFF,
    ],

    [SenegalCity.OUEST_FOIRE]: [
      SenegalLandmark.OUEST_FOIRE_BANQUE_CBAO,
      SenegalLandmark.OUEST_FOIRE_AUTOROUTE_TERMINUS_BUS,
      SenegalLandmark.OUEST_FOIRE_CASE_DES_TOUTS_PETITS,
      SenegalLandmark.OUEST_FOIRE_FEDERATION_FOOTBALL,
      SenegalLandmark.OUEST_FOIRE_BARA_COUTURE,
      SenegalLandmark.OUEST_FOIRE_BRIOCHE_DOREE,
      SenegalLandmark.OUEST_FOIRE_PHARMACIE_SABARA,
      SenegalLandmark.OUEST_FOIRE_ROND_POINT_YOFF,
      SenegalLandmark.OUEST_FOIRE_MARCHÉ_SERIGNE_FALLOU,
      SenegalLandmark.OUEST_FOIRE_ECOLE_DE_FORMATION_MEDECINE_SAMBA_DIALLO,
      SenegalLandmark.OUEST_FOIRE_PHARMACIE_XANDAR,
      SenegalLandmark.OUEST_FOIRE_MAGASIN_ZARA,
      SenegalLandmark.OUEST_FOIRE_CITE_KHANDAR,
      SenegalLandmark.OUEST_FOIRE_STATION_SHELL,
      SenegalLandmark.OUEST_FOIRE_STATION_ELTON,
      SenegalLandmark.OUEST_FOIRE_MUR_AÉROPORT,
      SenegalLandmark.OUEST_FOIRE_POSTE_COURANT,
      SenegalLandmark.OUEST_FOIRE_KEUR_BABOY,
      SenegalLandmark.OUEST_FOIRE_HOPITAL_PHILIPPE_SENGHOR,
      SenegalLandmark.OUEST_FOIRE_AUCHAN_YOFF,
      SenegalLandmark.OUEST_FOIRE_ALEA_DINE,
      SenegalLandmark.OUEST_FOIRE_TALLY_WALLY,
      SenegalLandmark.OUEST_FOIRE_CITE_MOURTADA,
      SenegalLandmark.OUEST_FOIRE_KEUR_PAPE_DIOUF,
      SenegalLandmark.OUEST_FOIRE_IMPOT_DOMAINE,
      SenegalLandmark.OUEST_FOIRE_COUCOU,
      SenegalLandmark.OUEST_FOIRE_PHARMACIE_VICTOIRE,
      SenegalLandmark.OUEST_FOIRE_GENDARMERIE,
      SenegalLandmark.OUEST_FOIRE_BANQUE_AGRICOLE,
      SenegalLandmark.OUEST_FOIRE_ALIA_DIEN,
    ],

    [SenegalCity.HLM_GRAND_YOFF]: [
      SenegalLandmark.HLM_GRAND_YOFF_DIBITERIE_KOROMACK_FAYE,
      SenegalLandmark.HLM_GRAND_YOFF_HOTEL_SOUM_SOUM,
      SenegalLandmark.HLM_GRAND_YOFF_ECOLE_PEDAGOGUE,
      SenegalLandmark.HLM_GRAND_YOFF_TERMINUS_AIBD,
      SenegalLandmark.HLM_GRAND_YOFF_BRT_HYACINTHE_THIANDOUM,
      SenegalLandmark.HLM_GRAND_YOFF_ECOLE_YASINE_THIANDOU,
      SenegalLandmark.HLM_GRAND_YOFF_HOPITAL_AMERICAIN,
      SenegalLandmark.HLM_GRAND_YOFF_RESIDENCES_ATAYA,
      SenegalLandmark.HLM_GRAND_YOFF_EN_FACE_STADE_AMITIE,
      SenegalLandmark.HLM_GRAND_YOFF_SHELTER,
      SenegalLandmark.HLM_GRAND_YOFF_ARRET_DDD,
    ],

    [SenegalCity.SICAP_FOIRE]: [
      SenegalLandmark.SICAP_FOIRE_TOUBA_OIL,
      SenegalLandmark.SICAP_FOIRE_PORTE_CICES,
      SenegalLandmark.SICAP_FOIRE_YOFF_DIBITERIE_KOROMACK_FAYE,
      SenegalLandmark.SICAP_FOIRE_CITE_MAGISTRAT,
      SenegalLandmark.SICAP_FOIRE_GENDARMERIE,
      SenegalLandmark.SICAP_FOIRE_LONASE,
      SenegalLandmark.SICAP_FOIRE_RÉSIDENCE_DABA,
      SenegalLandmark.SICAP_FOIRE_VDN,
      SenegalLandmark.SICAP_FOIRE_PRESTIGE_DECO,
      SenegalLandmark.SICAP_FOIRE_IMPOT_ET_DOMAINE,
      SenegalLandmark.SICAP_FOIRE_MUR,
    ],

    [SenegalCity.SUD_FOIRE]: [
      SenegalLandmark.SUD_FOIRE_ECOLE_IQRA,
      SenegalLandmark.SUD_FOIRE_CITE_SONATEL,
      SenegalLandmark.SUD_FOIRE_SAMU,
      SenegalLandmark.SUD_FOIRE_MOSQUEE,
    ],

    [SenegalCity.OUAKAM]: [
      SenegalLandmark.OUAKAM_STATION_SHELL,
      SenegalLandmark.OUAKAM_TERMINUS_P7,
      SenegalLandmark.OUAKAM_TERMINUS_43,
      SenegalLandmark.OUAKAM_COMICO,
      SenegalLandmark.OUAKAM_CITE_AVION,
      SenegalLandmark.OUAKAM_BRIOCHE_DOREE,
      SenegalLandmark.OUAKAM_MACKYOU_FAYE,
      SenegalLandmark.OUAKAM_ROND_POINT_MONUMENT,
      SenegalLandmark.OUAKAM_SUPER_MARCHE_MON_PRIX,
      SenegalLandmark.OUAKAM_MAMELLE,
      SenegalLandmark.OUAKAM_CROISEMENT,
      SenegalLandmark.OUAKAM_CITE_BALLON,
      SenegalLandmark.OUAKAM_AUCHAN,
      SenegalLandmark.OUAKAM_PHARMACIE_YAYE_AMINATA,
      SenegalLandmark.OUAKAM_POSTE_SANTE,
      SenegalLandmark.OUAKAM_CASE_DES_TOUT_PETITS,
      SenegalLandmark.OUAKAM_EGLISE_BLEUE,
      SenegalLandmark.OUAKAM_GENDARMERIE,
      SenegalLandmark.OUAKAM_CORNICHE,
      SenegalLandmark.OUAKAM_BATRAIN,
      SenegalLandmark.OUAKAM_CHEZ_BADJI,
      SenegalLandmark.OUAKAM_MUR_CAMPS,
      SenegalLandmark.OUAKAM_RESTAURANT_NIGÉRIEN,
      SenegalLandmark.OUAKAM_CITE_ASSEMBLEE,
      SenegalLandmark.OUAKAM_JEAN_MERMOZ,
      SenegalLandmark.OUAKAM_BOULANGERIE_LAYE_FAYE,
      SenegalLandmark.OUAKAM_CITE_EL_HADJ_MALICK_SY,
      SenegalLandmark.OUAKAM_MONTAGNE_ROUGE,
      SenegalLandmark.OUAKAM_MARCHE,
      SenegalLandmark.OUAKAM_PHARMACIE_MOUSSA,
      SenegalLandmark.OUAKAM_ARRET_CAR_RAPIDE,
      SenegalLandmark.OUAKAM_CITE_ASECNA,
      SenegalLandmark.OUAKAM_MOSQUEE_IBADOU,
      SenegalLandmark.OUAKAM_MOSQUEE_DIVINITE,
    ],

    [SenegalCity.LIBERTE_6]: [
      SenegalLandmark.LIBERTE_6_PHARMACIE_CAMP_LECLERC,
      SenegalLandmark.LIBERTE_6_PENTOLA,
      SenegalLandmark.LIBERTE_6_DIBITERIE_OUBA,
      SenegalLandmark.LIBERTE_6_STATION,
      SenegalLandmark.LIBERTE_6_MARCHE_BARACK,
      SenegalLandmark.LIBERTE_6_NUMERO_UNO,
      SenegalLandmark.LIBERTE_6_IMMEUBLE_FERDINAND_COLY,
      SenegalLandmark.LIBERTE_6_AUCHAN,
      SenegalLandmark.LIBERTE_6_VDN,
      SenegalLandmark.LIBERTE_6_SAMU,
      SenegalLandmark.LIBERTE_6_CSE,
      SenegalLandmark.LIBERTE_6_CITE_SONATEL,
      SenegalLandmark.LIBERTE_6_CITE_ALIOU_SOW,
      SenegalLandmark.LIBERTE_6_TERRAIN_FOOTBALL,
      SenegalLandmark.LIBERTE_6_CAMP_PENAL,
      SenegalLandmark.LIBERTE_6_PRISONS_POUR_FEMME,
      SenegalLandmark.LIBERTE_6_SONATEL_2,
      SenegalLandmark.LIBERTE_6_BRT,
      SenegalLandmark.LIBERTE_6_SIPRESS,
      SenegalLandmark.LIBERTE_6_ROND_POINT,
      SenegalLandmark.LIBERTE_6_PRESODIAG,
      SenegalLandmark.LIBERTE_6_TERMINUS_P9,
      SenegalLandmark.LIBERTE_6_DEUX_VOIES,
      SenegalLandmark.LIBERTE_6_VDN_SIEGE_WAVE,
      SenegalLandmark.LIBERTE_6_CITE_ASECNA,
      SenegalLandmark.LIBERTE_6_IMMEUBLE_JUMIA,
      SenegalLandmark.LIBERTE_6_CITE_PANORAMIQUE,
      SenegalLandmark.LIBERTE_6_BRIOCHE_DOREE,
      SenegalLandmark.LIBERTE_6_CAMP_LECLERC,
      SenegalLandmark.LIBERTE_6_DEM_DIK,
      SenegalLandmark.LIBERTE_6_CONACHAP,
      SenegalLandmark.LIBERTE_6_CITE_CPI,
    ],

    [SenegalCity.HLM]: [
      SenegalLandmark.HLM_SODIA,
      SenegalLandmark.HLM_POSTE_SANTE,
      SenegalLandmark.HLM_RAIL,
      SenegalLandmark.HLM_STATION,
      SenegalLandmark.HLM_CITE_DOUANE,
      SenegalLandmark.HLM_1,
      SenegalLandmark.HLM_2,
      SenegalLandmark.HLM_3,
      SenegalLandmark.HLM_4,
      SenegalLandmark.HLM_5,
      SenegalLandmark.HLM_6,
      SenegalLandmark.HLM_TER,
      SenegalLandmark.HLM_MARCHE,
      SenegalLandmark.HLM_KHELCOM_PIZZA,
      SenegalLandmark.HLM_OUAGOU_NIAYES,
      SenegalLandmark.HLM_POLICE,
      SenegalLandmark.HLM_VENISA,
    ],

    [SenegalCity.CASTOR]: [
      SenegalLandmark.CASTOR_SODIDA,
      SenegalLandmark.CASTOR_BRIOCHE_DOREE,
      SenegalLandmark.CASTOR_AUCHAN,
      SenegalLandmark.CASTOR_TERRAIN_FOOTBALL,
      SenegalLandmark.CASTOR_SENELEC,
      SenegalLandmark.CASTOR_HLM_BOURGUIBA,
      SenegalLandmark.CASTOR_MARCHE,
      SenegalLandmark.CASTOR_PHARMACIE_FRONT_DE_TERRE,
      SenegalLandmark.CASTOR_BANQUE_BCAO,
      SenegalLandmark.CASTOR_ECOLE_KHADIM_RASSOUL,
      SenegalLandmark.CASTOR_ECOLE_NOTRE_DAME_DU_LIBAN,
      SenegalLandmark.CASTOR_GENDARMERIE,
      SenegalLandmark.CASTOR_CITÉ_DES_EAUX,
      SenegalLandmark.CASTOR_PERON,
      SenegalLandmark.CASTOR_NOSCO,
      SenegalLandmark.CASTOR_CITE_GEOGRAPHIE,
      SenegalLandmark.CASTOR_UBA,
      SenegalLandmark.CASTOR_EMG,
    ],

    [SenegalCity.DIEUPPEUL_DERKLE]: [
      SenegalLandmark.DIEUPPEUL_DERKLE_TERRAIN_BASKET,
      SenegalLandmark.DIEUPPEUL_DERKLE_CITE_NOTAIRE,
      SenegalLandmark.DIEUPPEUL_DERKLE_ROND_POINT,
      SenegalLandmark.DIEUPPEUL_DERKLE_CLINIQUE_RABY,
      SenegalLandmark.DIEUPPEUL_DERKLE_UNIVERSITE_DAKAR_BOURGUIBA,
      SenegalLandmark.DIEUPPEUL_DERKLE_AVENUE_BOURGUIBA,
      SenegalLandmark.DIEUPPEUL_DERKLE_CEM,
      SenegalLandmark.DIEUPPEUL_DERKLE_MARCHE_SAMEDI,
      SenegalLandmark.DIEUPPEUL_DERKLE_TERMINUS_LIBERTE_5,
      SenegalLandmark.DIEUPPEUL_DERKLE_AMBASSADE_DU_TOGO,
      SenegalLandmark.DIEUPPEUL_DERKLE_CITE_MARINE,
      SenegalLandmark.DIEUPPEUL_DERKLE_DAROU_SALAM,
      SenegalLandmark.DIEUPPEUL_DERKLE_CITE_MARGUERY,
      SenegalLandmark.DIEUPPEUL_DERKLE_MOSQUEE,
      SenegalLandmark.DIEUPPEUL_DERKLE_FRONT_DE_TERRE,
      SenegalLandmark.DIEUPPEUL_DERKLE_TERMINUS_DEM_DIK,
      SenegalLandmark.DIEUPPEUL_DERKLE_ROND_POINT_LIBERTE_6,
      SenegalLandmark.DIEUPPEUL_DERKLE_CBAO,
      SenegalLandmark.DIEUPPEUL_DERKLE_CENTRE_SOCIOCULTUREL,
      SenegalLandmark.DIEUPPEUL_DERKLE_WALF,
      SenegalLandmark.DIEUPPEUL_DERKLE_MAIRIE,
      SenegalLandmark.DIEUPPEUL_DERKLE_BRT,
      SenegalLandmark.DIEUPPEUL_DERKLE_POLICE,
      SenegalLandmark.DIEUPPEUL_DERKLE_CLINIQUE_CROIX_BLEUE,
    ],

    [SenegalCity.PLATEAU]: [
      SenegalLandmark.PLATEAU_CITE_EMERGENCE,
      SenegalLandmark.PLATEAU_PONTY,
      SenegalLandmark.PLATEAU_GRANDE_MOSQUEE,
      SenegalLandmark.PLATEAU_TRIBUNAL_DEPARTEMENTALE_DE_DAKAR,
      SenegalLandmark.PLATEAU_RESTAURANT_COTE_OR,
      SenegalLandmark.PLATEAU_REUBEUSS,
      SenegalLandmark.PLATEAU_SANDAGA,
      SenegalLandmark.PLATEAU_PETERSEN,
      SenegalLandmark.PLATEAU_DAROU_SALAM,
      SenegalLandmark.PLATEAU_NIAYE_THIOKER,
      SenegalLandmark.PLATEAU_DIFONCE,
      SenegalLandmark.PLATEAU_MBOTH_SANDIAL,
      SenegalLandmark.PLATEAU_YAKH_DIEUF,
      SenegalLandmark.PLATEAU_KAAY_FINDIW,
      SenegalLandmark.PLATEAU_CITE_CAP_VERDIENNE,
      SenegalLandmark.PLATEAU_PLACE_DE_LINDEPENDANCE,
      SenegalLandmark.PLATEAU_ROUKHOU_DJINE,
      SenegalLandmark.PLATEAU_BIJOUTERIE_YORO_LAM,
      SenegalLandmark.PLATEAU_MOLE_8,
    ],
    [SenegalCity.PATTE_DOIE]: [
      SenegalLandmark.PATTE_DOIE_BRT,
      SenegalLandmark.PATTE_DOIE_STADE_MUNICIPAL,
      SenegalLandmark.PATTE_DOIE_STADE_YAKARR,
      SenegalLandmark.PATTE_DOIE_HOPITAL_NABIL_CHOUCAIR,
      SenegalLandmark.PATTE_DOIE_CITE_SOPRIME,
      SenegalLandmark.PATTE_DOIE_CITE_DES_IMPOTS,
      SenegalLandmark.PATTE_DOIE_BULDERS,
      SenegalLandmark.PATTE_DOIE_BRIOCHE_DOREE,
      SenegalLandmark.PATTE_DOIE_MAIRIE,
      SenegalLandmark.PATTE_DOIE_AUCHAN,
    ],

    [SenegalCity.BISCUITERIE]: [
      SenegalLandmark.BISCUITERIE_OUAGOU_NIAYES,
      SenegalLandmark.BISCUITERIE_ANCIEN_JARDIN_ENFANT,
      SenegalLandmark.BISCUITERIE_BOURGUIBA,
      SenegalLandmark.BISCUITERIE_MASSALIKOUL_DJINANE,
      SenegalLandmark.BISCUITERIE_BOPP,
    ],

    [SenegalCity.NIARY_TALLY]: [
      SenegalLandmark.NIARY_TALLY_BRIOCHE_DOREE,
      SenegalLandmark.NIARY_TALLY_JET_EAU,
      SenegalLandmark.NIARY_TALLY_SDE,
      SenegalLandmark.NIARY_TALLY_MARCHE_NGUELAW,
      SenegalLandmark.NIARY_TALLY_VENISIA,
      SenegalLandmark.NIARY_TALLY_PHARMACIE_COOPE,
      SenegalLandmark.NIARY_TALLY_SEN_EAU,
      SenegalLandmark.NIARY_TALLY_GRANDE_MOSQUEE,
    ],

    [SenegalCity.BENE_TALLY]: [
      SenegalLandmark.BENE_TALLY_CITE_CHEIKH_AHMADOU_BAMBA,
      SenegalLandmark.BENE_TALLY_YOUNOUSSE_AIDARA,
      SenegalLandmark.BENE_TALLY_PHARMACIE_BENE_TALLY,
      SenegalLandmark.BENE_TALLY_PHARMACIE_COOPE,
      SenegalLandmark.BENE_TALLY_VENISIA,
      SenegalLandmark.BENE_TALLY_HLM,
    ],

    [SenegalCity.PARCELLE_ASSAINIE]: [
      SenegalLandmark.PARCELLE_ASSAINIE_ROND_POINT_26,
      SenegalLandmark.PARCELLE_ASSAINIE_CITE_FADIA,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_26_STADE,
      SenegalLandmark.PARCELLE_ASSAINIE_CITE_DAMEL,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_13_POLICE,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_13_MARCHE,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_18_PHARMACIE_PARCELLOISE,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_7,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_8,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_12,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_13,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_15,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_17,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_19,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_20,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_21,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_24,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_26,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_9,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_10,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_11,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_14,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_16,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_18,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_22,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_23,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_25,
      SenegalLandmark.PARCELLE_ASSAINIE_CITE_DAMEL_VDN,
      SenegalLandmark.PARCELLE_ASSAINIE_CITE_DAMEL_ROND_POINT_26,
      SenegalLandmark.PARCELLE_ASSAINIE_EL_HADJ_MASSA_NIANG,
      SenegalLandmark.PARCELLE_ASSAINIE_CITE_DAMEL_EN_FACE_MIXTA,
      SenegalLandmark.PARCELLE_ASSAINIE_CITE_DAMEL_PONT_YENGOULEN,
      SenegalLandmark.PARCELLE_ASSAINIE_LEOPOLD_SEDAR_SENGHOR,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_16_BOULANGERIE_MANDELA,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_7_CASE_BA,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_17_JOLLOF_CHICKEN,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_24_MANGA,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_21_ECOLE_FRANCAISE,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_12_MARCHE_DIOR,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_24_STADE,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_26_POSTE_SANTE,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_19_ECOLE_DIOR,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_21_TERRAIN_FOOTBALL,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_5_ARRET_BRT_CASE_BAS,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_15_PLAGE,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_12_SENELEC,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_12_CITE_DE_DIOUMA_SEIGNEUR_CHEIKH,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_15_VDN,
      SenegalLandmark.PARCELLE_ASSAINIE_UNITE_23_POLICE,
    ],

    [SenegalCity.LIBERTE_1]: [SenegalLandmark.LIBERTE_1_BRT],

    [SenegalCity.LIBERTE_2]: [
      SenegalLandmark.LIBERTE_2_ANCIENNE_MAIRIE,
      SenegalLandmark.LIBERTE_2_STADIUM_MARIUS_NDIAYE,
      SenegalLandmark.LIBERTE_2_STADE_DEMBA_DIOP,
    ],

    [SenegalCity.LIBERTE_3]: [
      SenegalLandmark.LIBERTE_3_POLICE_DIEUPPEUL,
      SenegalLandmark.LIBERTE_3_AVENUE_BOURGUIBA,
      SenegalLandmark.LIBERTE_3_SUNU_BANK,
      SenegalLandmark.LIBERTE_3_NYARA,
    ],

    [SenegalCity.LIBERTE_4]: [
      SenegalLandmark.LIBERTE_4_TERRAIN_FOOTBALL,
      SenegalLandmark.LIBERTE_4_TERMINUS,
      SenegalLandmark.LIBERTE_4_IPG,
      SenegalLandmark.LIBERTE_4_MOSQUEE,
    ],

    [SenegalCity.LIBERTE_5]: [
      SenegalLandmark.LIBERTE_5_ROND_POINT_JVC,
      SenegalLandmark.LIBERTE_5_TERMINUS,
      SenegalLandmark.LIBERTE_5_AUCHAN,
      SenegalLandmark.LIBERTE_5_TERMINUS_DEM_DIK,
      SenegalLandmark.LIBERTE_5_SAMU,
      SenegalLandmark.LIBERTE_5_BRT,
    ],

    [SenegalCity.SCAT_URBAM]: [
      SenegalLandmark.SCAT_URBAM_TERRAIN_FOOTBALL,
      SenegalLandmark.SCAT_URBAM_STATION_OLIBIA,
      SenegalLandmark.SCAT_URBAM_MOSQUEE,
      SenegalLandmark.SCAT_URBAM_CEM,
      SenegalLandmark.SCAT_URBAM_KEUR_FATOU,
      SenegalLandmark.SCAT_URBAM_BRT,
      SenegalLandmark.SCAT_URBAM_AUCHAN,
      SenegalLandmark.SCAT_URBAM_HOPITAL_AMERICAIN,
      SenegalLandmark.SCAT_URBAM_BRIOCHE_DOREE,
      SenegalLandmark.SCAT_URBAM_ROND_POINT_MAIRIE,
      SenegalLandmark.SCAT_URBAM_PHARMACIE_SHELTER,
      SenegalLandmark.SCAT_URBAM_UNO,
      SenegalLandmark.SCAT_URBAM_PENTOLA,
      SenegalLandmark.SCAT_URBAM_CONACHAP,
      SenegalLandmark.SCAT_URBAM_STADE_LLS,
    ],

    [SenegalCity.GIBRALTAR]: [
      SenegalLandmark.GIBRALTAR_AUCHAN,
      SenegalLandmark.GIBRALTAR_MOSQUEE,
      SenegalLandmark.GIBRALTAR_EGLISE,
      SenegalLandmark.GIBRALTAR_CENTENAIRE,
      SenegalLandmark.GIBRALTAR_KEUR_SOEUR,
    ],

    [SenegalCity.CAMBERENE]: [
      SenegalLandmark.CAMBERENE_PHARMACIE_MARY_FAMA,
      SenegalLandmark.CAMBERENE_TALLI_NDIAGA_MBAYE,
      SenegalLandmark.CAMBERENE_BRT,
      SenegalLandmark.CAMBERENE_MARCHE,
      SenegalLandmark.CAMBERENE_MAIRIE,
      SenegalLandmark.CAMBERENE_POSTE_DE_SANTE,
      SenegalLandmark.CAMBERENE_ROND_POINT,
      SenegalLandmark.CAMBERENE_UNITE_5,
      SenegalLandmark.CAMBERENE_NATIONS_UNIES,
      SenegalLandmark.CAMBERENE_VDN,
      SenegalLandmark.CAMBERENE_ONAS,
      SenegalLandmark.CAMBERENE_MAISON_ANCIEN_DIRECTEUR_SENELEC,
      SenegalLandmark.CAMBERENE_STATION_API,
      SenegalLandmark.CAMBERENE_CIMETIERE,
    ],

    [SenegalCity.MEDINA]: [
      SenegalLandmark.MEDINA_BRIOCHE_DOREE,
      SenegalLandmark.MEDINA_ROND_POINT_SHAM,
      SenegalLandmark.MEDINA_RUE_41_X_22,
      SenegalLandmark.MEDINA_RUE_41,
      SenegalLandmark.MEDINA_RUE_08,
      SenegalLandmark.MEDINA_RUE_35_X_26,
      SenegalLandmark.MEDINA_RUE_6_X_19,
      SenegalLandmark.MEDINA_BRT,
      SenegalLandmark.MEDINA_RUE_6_X_9,
      SenegalLandmark.MEDINA_STADE,
      SenegalLandmark.MEDINA_CESAG,
      SenegalLandmark.MEDINA_RUE_3_X_16,
      SenegalLandmark.MEDINA_RUE_33_X_10,
      SenegalLandmark.MEDINA_RUE_15_X_12,
      SenegalLandmark.MEDINA_RUE_39_X_30,
      SenegalLandmark.MEDINA_PLACE_DE_LA_NATION,
      SenegalLandmark.MEDINA_LYCÉE_KENNEDY,
      SenegalLandmark.MEDINA_CORNICHE_OUEST,
      SenegalLandmark.MEDINA_RUE_6_X_3,
      SenegalLandmark.MEDINA_RUE_11,
      SenegalLandmark.MEDINA_RUE_31_X_BLAISE_DIAGNE,
      SenegalLandmark.MEDINA_RUE_25_X_2,
      SenegalLandmark.MEDINA_CARAMEL,
      SenegalLandmark.MEDINA_RUE_5_X_6,
      SenegalLandmark.MEDINA_RUE_19_X_10,
      SenegalLandmark.MEDINA_DOUTA_SECK,
      SenegalLandmark.MEDINA_SANDAGA,
      SenegalLandmark.MEDINA_RUE_5,
      SenegalLandmark.MEDINA_RUE_15_X_CORNICHE,
      SenegalLandmark.MEDINA_RUE_17_X_22,
      SenegalLandmark.MEDINA_RUE_9_X_BLAISE_DIAGNE,
      SenegalLandmark.MEDINA_RUE_6,
      SenegalLandmark.MEDINA_RUE_8,
      SenegalLandmark.MEDINA_RUE_25_X_C,
    ],

    [SenegalCity.HLM_GRAND_MEDINE]: [SenegalLandmark.HLM_GRAND_MEDINE_VDN],

    [SenegalCity.FASS]: [
      SenegalLandmark.FASS_MARCHE,
      SenegalLandmark.FASS_COLOBANE,
      SenegalLandmark.FASS_BRT,
      SenegalLandmark.FASS_PAILLOTE,
    ],

    [SenegalCity.NGOR]: [
      SenegalLandmark.NGOR_CHEZ_KATHIA,
      SenegalLandmark.NGOR_VIRAGE,
      SenegalLandmark.NGOR_BRIOCHE_DOREE,
      SenegalLandmark.NGOR_STADE,
      SenegalLandmark.NGOR_CREDIT_MUTUELLE,
      SenegalLandmark.NGOR_NDIOGORANE,
      SenegalLandmark.NGOR_PHARMACIE_NGOR,
      SenegalLandmark.NGOR_MAIRIE,
      SenegalLandmark.NGOR_TERMINUS_35,
    ],

    [SenegalCity.ALMADIES]: [
      SenegalLandmark.ALMADIES_ECOLE_BILLINGUE,
      SenegalLandmark.ALMADIES_PHILIPPE_MORRIS,
      SenegalLandmark.ALMADIES_NIRVANA,
      SenegalLandmark.ALMADIES_RECASEMENT,
      SenegalLandmark.ALMADIES_KATIA,
      SenegalLandmark.ALMADIES_STATION_SHELL,
      SenegalLandmark.ALMADIES_AGENCE_ORANGE,
      SenegalLandmark.ALMADIES_KING_FAHD_PALACE,
      SenegalLandmark.ALMADIES_BOA,
      SenegalLandmark.ALMADIES_ZONE_DE_RECASEMENT,
      SenegalLandmark.ALMADIES_BI_HOTEL,
      SenegalLandmark.ALMADIES_TEMOIN_DE_JEHOVAH,
      SenegalLandmark.ALMADIES_EDK,
      SenegalLandmark.ALMADIES_GONDOLE,
    ],

    [SenegalCity.GUEULE_TAPEE]: [SenegalLandmark.GUEULE_TAPEE_SOUMBEDIOUNE],

    [SenegalCity.FANN_HOCK]: [],

    [SenegalCity.SACRE_COEUR]: [
      SenegalLandmark.SACRE_COEUR_VDN,
      SenegalLandmark.SACRE_COEUR_RESIDENCE_MAMOUNE,
      SenegalLandmark.SACRE_COEUR_BOULANGERIE_JAUNE,
      SenegalLandmark.SACRE_COEUR_CITE_BATRAIN,
      SenegalLandmark.SACRE_COEUR_BRT,
      SenegalLandmark.SACRE_COEUR_AMINATA_TALL,
      SenegalLandmark.SACRE_COEUR_IPG,
      SenegalLandmark.SACRE_COEUR_COLLEGE,
      SenegalLandmark.SACRE_COEUR_CITE_KEUR_GORGUI,
      SenegalLandmark.SACRE_COEUR_ECOLE_BEM,
    ],

    [SenegalCity.MERMOZ]: [
      SenegalLandmark.MERMOZ_CHINA_MALL,
      SenegalLandmark.MERMOZ_SICAP_BAOBAB,
      SenegalLandmark.MERMOZ_CITE_KEUR_GORGUI,
      SenegalLandmark.MERMOZ_SOTRAC,
      SenegalLandmark.MERMOZ_AMITIE_3_CASINO_LIBERTE,
      SenegalLandmark.MERMOZ_VDN,
      SenegalLandmark.MERMOZ_SIPRES_3,
      SenegalLandmark.MERMOZ_AUCHAN,
      SenegalLandmark.MERMOZ_CITE_BATRAIN,
      SenegalLandmark.MERMOZ_CASE_DES_TOUT_PETITS,
      SenegalLandmark.MERMOZ_CITE_KEUR_GORGUI_AUCHAN,
      SenegalLandmark.MERMOZ_CITE_KEUR_GORGUI_BRIOCHE_DOREE,
    ],

    [SenegalCity.MAMELLE]: [
      SenegalLandmark.MAMELLE_CITE_CHEIKH_AMAR,
      SenegalLandmark.MAMELLE_CITE_MBACKIYOU_FAYE,
      SenegalLandmark.MAMELLE_CITE_TOUBA_RENAISSANCE,
      SenegalLandmark.MAMELLE_RESTAURANT_MELO,
      SenegalLandmark.MAMELLE_ECOLE_SEMAD,
      SenegalLandmark.MAMELLE_ROND_POINT,
      SenegalLandmark.MAMELLE_PHARMACIE_ADJA_DABA_DIAGNE,
      SenegalLandmark.MAMELLE_RENAISSANCE,
      SenegalLandmark.MAMELLE_CITE_DES_ENSEIGNANTS,
      SenegalLandmark.MAMELLE_MONUMENT,
      SenegalLandmark.MAMELLE_CITE_ASECNA,
      SenegalLandmark.MAMELLE_IMMEUBLE_MARIAMA,
      SenegalLandmark.MAMELLE_ARRET_P7,
      SenegalLandmark.MAMELLE_EUROMED,
    ],

    [SenegalCity.ZONE_DE_CAPTAGE]: [
      SenegalLandmark.ZONE_DE_CAPTAGE_BRIOCHE_DOREE,
      SenegalLandmark.ZONE_DE_CAPTAGE_STATION,
      SenegalLandmark.ZONE_DE_CAPTAGE_MOSQUEE,
      SenegalLandmark.ZONE_DE_CAPTAGE_MARCHE_DU_PORC,
      SenegalLandmark.ZONE_DE_CAPTAGE_TERMINUS_83,
      SenegalLandmark.ZONE_DE_CAPTAGE_FRONT_DE_TERRE,
      SenegalLandmark.ZONE_DE_CAPTAGE_SODIDA_MARISTE,
    ],

    [SenegalCity.KHAR_YALLA]: [
      SenegalLandmark.KHAR_YALLA_BRT,
      SenegalLandmark.KHAR_YALLA_STATION,
      SenegalLandmark.KHAR_YALLA_ECOLE_NOTRE_DAME_DU_LIBAN,
      SenegalLandmark.KHAR_YALLA_PHARMACIE_BAGDAD,
      SenegalLandmark.KHAR_YALLA_TALI_CARREAUX,
    ],

    [SenegalCity.FANN]: [SenegalLandmark.FANN_AUCHAN],

    [SenegalCity.POINT_E]: [
      SenegalLandmark.POINT_E_RESIDENCE_CACHEMIR,
      SenegalLandmark.POINT_E_AUCHAN,
      SenegalLandmark.POINT_E_PISCINE_OLYMPIQUE,
      SenegalLandmark.POINT_E_ISM,
      SenegalLandmark.POINT_E_AMITIE,
      SenegalLandmark.POINT_E_MOSQUEE,
    ],

    [SenegalCity.SICAP_KARACK]: [
      SenegalLandmark.SICAP_KARACK_MAMADOU_ET_BINETA,
      SenegalLandmark.SICAP_KARACK_MOSQUEE,
      SenegalLandmark.SICAP_KARACK_YALLA,
    ],

    [SenegalCity.HANN_MARISTE]: [
      SenegalLandmark.HANN_MARISTE_STATION_TOTAL,
      SenegalLandmark.HANN_MARISTE_ECOLE_JAPONAISE,
      SenegalLandmark.HANN_MARISTE_EDK,
      SenegalLandmark.HANN_MARISTE_ECOLE_CEM,
      SenegalLandmark.HANN_MARISTE_BANQUE_CBAO,
      SenegalLandmark.HANN_MARISTE_BRIOCHE_DOREE,
      SenegalLandmark.HANN_MARISTE_DJAMIL_CARREAUX,
      SenegalLandmark.HANN_MARISTE_PHARMACIE,
      SenegalLandmark.HANN_MARISTE_RESIDENCE_LES_DUNES,
      SenegalLandmark.HANN_MARISTE_CHOUMIMI,
      SenegalLandmark.HANN_MARISTE_PHARMACIE_TOUBA,
    ],

    [SenegalCity.HANN_BEL_AIR]: [
      SenegalLandmark.HANN_BEL_AIR_YARAKH,
      SenegalLandmark.HANN_BEL_AIR_YARAKH_DALIFORT,
      SenegalLandmark.HANN_BEL_AIR_PORT,
    ],
  },
  [SenegalDepartment.GUEDIAWAYE]: {
    [SenegalCity.CITE_FADIA]: [
      SenegalLandmark.CITE_FADIA_BRT,
      SenegalLandmark.CITE_FADIA_CORNICHE,
    ],
    [SenegalCity.GOLF_SUD]: [
      SenegalLandmark.GOLF_SUD_CITE_ALIOUNE_SOW_SUPECO,
      SenegalLandmark.GOLF_SUD_CITE_ALIOUNE_SOW_BRT,
      SenegalLandmark.GOLF_SUD_CITE_FADIA,
      SenegalLandmark.GOLF_SUD_LAS_PALMAS,
      SenegalLandmark.GOLF_SUD_ANCIENNE_POLICE,
      SenegalLandmark.GOLF_SUD_MARCHE_JEUDI,
      SenegalLandmark.GOLF_SUD_STATION_DIAL_MBAYE,
    ],
    [SenegalCity.GADAYE]: [
      SenegalLandmark.GADAYE_STADE,
      SenegalLandmark.GADAYE_VDN3,
    ],
  },
  [SenegalDepartment.KEUR_MASSAR]: {
    [SenegalCity.MALIKA]: [
      SenegalLandmark.MALIKA_CITE_SONATEL,
      SenegalLandmark.MALIKA_PLAGE,
      SenegalLandmark.MALIKA_PLAGE_PHARMACIE,
      SenegalLandmark.MALIKA_CITE_SEYDINA_LIMAMOU_LAYE,
    ],
    [SenegalCity.ALMADIE_2]: [
      SenegalLandmark.ALMADIE_2_SORTIE_9,
      SenegalLandmark.ALMADIE_2_BRIOCHE_DOREE,
    ],
    [SenegalCity.JAXAAY]: [
      SenegalLandmark.JAXAAY_TERMINUS_VERT_BLANC,
      SenegalLandmark.JAXAAY_UNITE_5,
      SenegalLandmark.JAXAAY_UNITE_12,
      SenegalLandmark.JAXAAY_UNITE_15,
      SenegalLandmark.JAXAAY_UNITE_24,
    ],
  },
  [SenegalDepartment.PIKINE]: {
    [SenegalCity.ZAC_MBAO]: [
      SenegalLandmark.ZAC_MBAO_ROND_POINT_SIPRES,
      SenegalLandmark.ZAC_MBAO_CITE_SONATEL,
      SenegalLandmark.ZAC_MBAO_CITE_ASSURANCE,
      SenegalLandmark.ZAC_MBAO_CITE_ENVIRONNEMENT,
      SenegalLandmark.ZAC_MBAO_CITE_FINANCE,
      SenegalLandmark.ZAC_MBAO_CLINIQUE_NABY,
      SenegalLandmark.ZAC_MBAO_ROND_POINT_AXA,
      SenegalLandmark.ZAC_MBAO_AUCHAN,
      SenegalLandmark.ZAC_MBAO_INSTITUT_MOZDAHIR_INTERNATIONAL,
      SenegalLandmark.ZAC_MBAO_MARCHE,
      SenegalLandmark.ZAC_MBAO_CITE_NESTLE,
      SenegalLandmark.ZAC_MBAO_CITE_KORA_FALL,
      SenegalLandmark.ZAC_MBAO_DEUX_VOIES_SIPRES,
    ],
    [SenegalCity.GRAND_MBAO]: [
      SenegalLandmark.GRAND_MBAO_CITE_BAOBAB,
      SenegalLandmark.GRAND_MBAO_CITE_ELEVAGE,
      SenegalLandmark.GRAND_MBAO_LYCEE_MBAO,
      SenegalLandmark.GRAND_MBAO_ANCIEN_SENELEC,
      SenegalLandmark.GRAND_MBAO_CITE_BAY_NIASS,
      SenegalLandmark.GRAND_MBAO_ROND_POINT,
    ],
    [SenegalCity.PETIT_MBAO]: [
      SenegalLandmark.PETIT_MBAO_CITE_ADJA_MAREME,
      SenegalLandmark.PETIT_MBAO_CROISEMENT_KEUR_MASSAR,
      SenegalLandmark.PETIT_MBAO_VILLENEUVE,
      SenegalLandmark.PETIT_MBAO_CITE_DABAKH,
      SenegalLandmark.PETIT_MBAO_ARRET_SEN_MOUNTAKHA,
      SenegalLandmark.PETIT_MBAO_ARRET_BOULANGERIE_BOULEVARD,
    ],
    [SenegalCity.THIAROYE]: [
      SenegalLandmark.THIAROYE_AZURE_CITE_KHADIJA,
      SenegalLandmark.THIAROYE_FASS_MBAO,
      SenegalLandmark.THIAROYE_TALLY_DIALLO,
    ],
    [SenegalCity.KEUR_MBAYE_FALL]: [
      SenegalLandmark.KEUR_MBAYE_FALL_CITE_POSTE,
      SenegalLandmark.KEUR_MBAYE_FALL_TALLY_CARREAUX,
      SenegalLandmark.KEUR_MBAYE_FALL_TER,
    ],
    [SenegalCity.YEUMBEUL]: [
      SenegalLandmark.YEUMBEUL_BEN_BARACK,
      SenegalLandmark.YEUMBEUL_TER,
      SenegalLandmark.YEUMBEUL_ASECNA,
    ],
    [SenegalCity.FASS_MBAO]: [SenegalLandmark.FASS_MBAO_CITE_COMICO],
    [SenegalCity.DALIFORT]: [
      SenegalLandmark.DALIFORT_MARISTE,
      SenegalLandmark.DALIFORT_CEM,
      SenegalLandmark.DALIFORT_CROISEMENT_CAMBERENE,
    ],
    [SenegalCity.DAGOUDANE]: [SenegalLandmark.DAGOUDANE_TALLI_CARREAU],
    [SenegalCity.TALI_BOU_MAK]: [SenegalLandmark.TALI_BOU_MAK_CBAO],
  },
  [SenegalDepartment.RUFISQUE]: {
    [SenegalCity.LAC_ROSE]: [SenegalLandmark.LAC_ROSE_MAISON_AKON],
    [SenegalCity.NDIAKHIRATE]: [SenegalLandmark.NDIAKHIRATE_CITE_DAKAR_NAVE],
    [SenegalCity.GOUYE_MOURIDE]: [
      SenegalLandmark.GOUYE_MOURIDE_TERRAIN_FOOTBALL,
    ],
    [SenegalCity.BARGNY]: [SenegalLandmark.BARGNY_NORD],
    [SenegalCity.KOUNOUNE]: [
      SenegalLandmark.KOUNOUNE_CITE_ICS,
      SenegalLandmark.KOUNOUNE_CENTRALE,
      SenegalLandmark.KOUNOUNE_TERMINUS_BUS_45,
    ],

    [SenegalCity.DIAMNIADIO]: [
      SenegalLandmark.DIAMNIADIO_NORD_POSTE_DOUANE,
      SenegalLandmark.DIAMNIADIO_DOUGAR,
    ],
    [SenegalCity.BAMBILOR]: [SenegalLandmark.BAMBILOR_CITE_COMICO],
    [SenegalCity.KEUR_NDIAYE_LO]: [
      SenegalLandmark.KEUR_NDIAYE_LO_SORTIE_10,
      SenegalLandmark.KEUR_NDIAYE_LO_CITE_NOUVELLE_HORIZON,
      SenegalLandmark.KEUR_NDIAYE_LO_CITE_NOUVELLE_HORIZON_PHARMACIE,
    ],
    [SenegalCity.TIVAOUANE_PEULH]: [
      SenegalLandmark.TIVAOUANE_PEULH_CITE_APIX,
      SenegalLandmark.TIVAOUANE_PEULH_MARCHE,
      SenegalLandmark.TIVAOUANE_PEULH_ROND_POINT_MARONE,
      SenegalLandmark.TIVAOUANE_PEULH_ARRET_BAYE_NIASS,
    ],
  },
  [SenegalDepartment.THIES]: {
    [SenegalCity.GRAND_STANDING]: [SenegalLandmark.GRAND_STANDING_EDK],
    [SenegalCity.PARCELLE_ASSAINIE_THIES]: [
      SenegalLandmark.PARCELLE_ASSAINIE_THIES_UNITE_5_CIMETIERE,
    ],
    [SenegalCity.MBOUR_4]: [SenegalLandmark.MBOUR_4_CITE_ENSEIGNANTS],
    [SenegalCity.DIXIEME]: [SenegalLandmark.DIXIEME_PRISON],
    [SenegalCity.KEUR_ISSA]: [
      SenegalLandmark.KEUR_ISSA_ARRET_TATA_7,
      SenegalLandmark.KEUR_ISSA_POSTE_SANTE,
    ],
    [SenegalCity.MEDINA_FALL]: [
      SenegalLandmark.MEDINA_FALL_LYCEE,
      SenegalLandmark.MEDINA_FALL_DON_BOSCO,
      SenegalLandmark.MEDINA_FALL_PHARMACIE_LAMPE_FALL,
    ],
  },
  [SenegalDepartment.PETITE_COTE]: {
    [SenegalCity.SALY]: [
      SenegalLandmark.SALY_BAMBARA,
      SenegalLandmark.SALY_JOSEPH,
      SenegalLandmark.SALY_GOLF,
      SenegalLandmark.SALY_DIAMBAR,
      SenegalLandmark.SALY_STATION,
    ],
    [SenegalCity.TOUBAB_DIALAW]: [
      SenegalLandmark.TOUBAB_DIALAW_HOTEL_IRIS,
      SenegalLandmark.TOUBAB_DIALAW_HOTEL_ESCALE,
      SenegalLandmark.TOUBAB_DIALAW_ECOLE_KIDS_ACADEMY,
    ],
    [SenegalCity.NIANING]: [SenegalLandmark.NIANING_STATION_ELTON],
    [SenegalCity.MALIKOUNDA]: [SenegalLandmark.MALIKOUNDA_SORTIE_PEAGE],
    [SenegalCity.MBOUR]: [
      SenegalLandmark.MBOUR_SANDIARA,
      SenegalLandmark.MBOUR_MEDINE,
    ],
    [SenegalCity.NGAPAROU]: [],
    [SenegalCity.SOMONE]: [],
    [SenegalCity.NDAYANE]: [SenegalLandmark.NDAYANE_HOTEL_PIERRE_DE_LISSE],
    [SenegalCity.YENNE_SUR_MER]: [
      SenegalLandmark.YENNE_SUR_MER_STATION_TITAN_OIL,
    ],
  },
};
